version: '3.7'
services:
  mysql:
    image: mysql:5.7
    container_name: my-mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tamara
      MYSQL_DATABASE: UserRegister
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
